[package]
name = "empty_circuit"
type = "bin"
authors = [""]

[dependencies]
bignum = { tag = "v0.6.0", git = "https://github.com/noir-lang/noir-bignum" }
keccak256 = { tag = "v0.1.0", git = "https://github.com/noir-lang/keccak256" }
sha256 = { tag = "v0.1.2", git = "https://github.com/noir-lang/sha256" }
